version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony
    container_name: php-fpm
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
volumes:
  mysql: